### ISSUE TITLE
A Command With No Data Causes Crash

### ISSUE THREAD

**Issue by JamesMc86** [JamesMc86/LabVIEW-CLI#33]
For some reason we have a guard that we don't read the TCP buffer if length is only TYPE_BYTES. This means the TYPE is left in the buffer and corrupts the next read.

This will result in the following exception:

```
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: size
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at LabVIEW_CLI.lvComms.readMessage()
   at LabVIEW_CLI.Program.Main(String[] args)
```

**Comment by JamesMc86** [comment]
Fixed in v1.5.1
